export const CLASS_ABILITY_TEMPLATES = {
  guardian: [
    {
      id: 'shield_slam',
      name: 'Shield Slam',
      slot: 2,
      cooldownMs: 6000,
      requiredLevel: 2,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'melee',
      resourceCost: 30,
      baseValue: 10,
      coefficient: 0.4,
      stunDurationMs: 800,
      stunImmunityMs: 6000,
    },
    {
      id: 'defensive_stance',
      name: 'Defensive Stance',
      slot: 3,
      cooldownMs: 12000,
      requiredLevel: 3,
      targetType: 'self',
      resourceCost: 40,
      durationMs: 4000,
      damageTakenMultiplier: 0.7,
      pvpDamageTakenMultiplier: 0.8,
      moveSpeedMultiplier: 0.8,
    },
    {
      id: 'taunt',
      name: 'Taunt',
      slot: 4,
      cooldownMs: 8000,
      requiredLevel: 6,
      targetType: 'targeted',
      targetKind: 'mob',
      resourceCost: 25,
      range: 2.5,
      durationMs: 3000,
    },
    {
      id: 'shield_wall',
      name: 'Shield Wall',
      slot: 5,
      cooldownMs: 30000,
      requiredLevel: 10,
      targetType: 'self',
      resourceCost: 50,
      durationMs: 3000,
      damageTakenMultiplier: 0.5,
      pvpDamageTakenMultiplier: 0.7,
    },
    {
      id: 'fortify',
      name: 'Fortify',
      slot: 6,
      cooldownMs: 45000,
      requiredLevel: 15,
      targetType: 'self',
      resourceCost: 40,
      durationMs: 8000,
      maxHpMultiplier: 1.2,
    },
    {
      id: 'ground_slam',
      name: 'Ground Slam',
      slot: 7,
      cooldownMs: 15000,
      requiredLevel: 20,
      targetType: 'aoe',
      attackType: 'melee',
      resourceCost: 45,
      baseValue: 12,
      coefficient: 0.4,
      radius: 2.5,
      slowPct: 40,
      durationMs: 3000,
      pvpCCDurationMultiplier: 0.625,
    },
    {
      id: 'guardians_rebuke',
      name: "Guardian's Rebuke",
      slot: 8,
      cooldownMs: 12000,
      requiredLevel: 25,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'melee',
      resourceCost: 30,
      baseValue: 8,
      coefficient: 0.35,
      interruptLockoutMs: 2000,
    },
    {
      id: 'unbreakable',
      name: 'Unbreakable',
      slot: 9,
      cooldownMs: 120000,
      requiredLevel: 30,
      targetType: 'self',
      resourceCost: 60,
      durationMs: 4000,
      pvpDurationMs: 2000,
      ccImmune: true,
    },
  ],
  fighter: [
    {
      id: 'power_strike',
      name: 'Power Strike',
      slot: 2,
      cooldownMs: 5000,
      requiredLevel: 2,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'melee',
      resourceCost: 40,
      baseValue: 20,
      coefficient: 0.8,
    },
    {
      id: 'cleave',
      name: 'Cleave',
      slot: 3,
      cooldownMs: 8000,
      requiredLevel: 3,
      targetType: 'aoe',
      attackType: 'melee',
      resourceCost: 50,
      baseValue: 15,
      coefficient: 0.5,
      coneDegrees: 120,
      range: 2.5,
    },
    {
      id: 'berserk',
      name: 'Berserk',
      slot: 4,
      cooldownMs: 60000,
      requiredLevel: 6,
      targetType: 'self',
      resourceCost: 30,
      durationMs: 6000,
      damageDealtMultiplier: 1.25,
      pvpDamageDealtMultiplier: 1.15,
    },
    {
      id: 'whirlwind',
      name: 'Whirlwind',
      slot: 5,
      cooldownMs: 10000,
      requiredLevel: 10,
      targetType: 'aoe',
      attackType: 'melee',
      resourceCost: 55,
      baseValue: 18,
      coefficient: 0.6,
      coneDegrees: 360,
      range: 2.5,
    },
    {
      id: 'execute',
      name: 'Execute',
      slot: 6,
      cooldownMs: 8000,
      requiredLevel: 15,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'melee',
      resourceCost: 40,
      baseValue: 10,
      coefficient: 1.2,
      executeThresholdPct: 30,
    },
    {
      id: 'blood_rage',
      name: 'Blood Rage',
      slot: 7,
      cooldownMs: 90000,
      requiredLevel: 20,
      targetType: 'self',
      resourceCost: 0,
      durationMs: 6000,
      consumeAllRage: true,
    },
    {
      id: 'interrupting_strike',
      name: 'Interrupting Strike',
      slot: 8,
      cooldownMs: 12000,
      requiredLevel: 25,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'melee',
      resourceCost: 35,
      baseValue: 8,
      coefficient: 0.5,
      interruptLockoutMs: 2000,
    },
    {
      id: 'avatar_of_war',
      name: 'Avatar of War',
      slot: 9,
      cooldownMs: 120000,
      requiredLevel: 30,
      targetType: 'self',
      resourceCost: 60,
      durationMs: 10000,
      physicalPowerMultiplier: 1.3,
      pvpPhysicalPowerMultiplier: 1.2,
    },
  ],
  ranger: [
    {
      id: 'aimed_shot',
      name: 'Aimed Shot',
      slot: 2,
      cooldownMs: 6000,
      requiredLevel: 2,
      targetType: 'targeted',
      targetKind: 'mob',
      attackType: 'ranged',
      resourceCost: 35,
      windUpMs: 600,
      baseValue: 25,
      coefficient: 1.0,
      rangeMultiplier: 1.2,
    },
    {
      id: 'roll_back',
      name: 'Roll Back',
      slot: 3,
      cooldownMs: 10000,
      requiredLevel: 3,
      targetType: 'self',
      resourceCost: 30,
      dashDistance: 3,
      durationMs: 1000,
      exemptFromGCD: true,
    },
    {
      id: 'poison_arrow',
      name: 'Poison Arrow',
      slot: 4,
      cooldownMs: 12000,
      requiredLevel: 6,
      targetType: 'targeted',
      targetKind: 'mob',
      attackType: 'ranged',
      resourceCost: 30,
      baseValue: 6,
      coefficient: 0.2,
      dotTicks: 6,
      dotDurationMs: 6000,
    },
    {
      id: 'rapid_fire',
      name: 'Rapid Fire',
      slot: 5,
      cooldownMs: 15000,
      requiredLevel: 10,
      targetType: 'targeted',
      targetKind: 'mob',
      attackType: 'ranged',
      resourceCost: 40,
      windUpMs: 1500,
      channelTicks: 3,
      baseValue: 12,
      coefficient: 0.5,
    },
    {
      id: 'snare_trap',
      name: 'Snare Trap',
      slot: 6,
      cooldownMs: 20000,
      requiredLevel: 15,
      targetType: 'aoe',
      attackType: 'ranged',
      resourceCost: 35,
      baseValue: 5,
      coefficient: 0.2,
      radius: 2.5,
      rootDurationMs: 2000,
      pvpCCDurationMultiplier: 0.5,
      requirePlacement: true,
      placementRange: 10,
    },
    {
      id: 'mark_target',
      name: 'Mark Target',
      slot: 7,
      cooldownMs: 15000,
      requiredLevel: 20,
      targetType: 'targeted',
      targetKind: 'any',
      resourceCost: 25,
      durationMs: 10000,
      markDamageBonusPct: 10,
    },
    {
      id: 'disengage_shot',
      name: 'Disengage Shot',
      slot: 8,
      cooldownMs: 18000,
      requiredLevel: 25,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'ranged',
      resourceCost: 40,
      baseValue: 15,
      coefficient: 0.6,
      knockbackDistance: 2,
    },
    {
      id: 'eagle_eye',
      name: 'Eagle Eye',
      slot: 9,
      cooldownMs: 60000,
      requiredLevel: 30,
      targetType: 'self',
      resourceCost: 50,
      durationMs: 8000,
      critChanceBonusPct: 20,
      pvpCritChanceBonusPct: 10,
    },
  ],
  priest: [
    {
      id: 'heal',
      name: 'Heal',
      slot: 2,
      cooldownMs: 4000,
      requiredLevel: 2,
      targetType: 'targeted',
      targetKind: 'player',
      resourceCost: 35,
      range: 5,
      baseValue: 15,
      coefficient: 0.9,
      supportTag: true,
    },
    {
      id: 'smite',
      name: 'Smite',
      slot: 3,
      cooldownMs: 5000,
      requiredLevel: 3,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'ranged',
      resourceCost: 30,
      baseValue: 12,
      coefficient: 0.7,
      weakenedPct: 15,
    },
    {
      id: 'renew',
      name: 'Renew',
      slot: 4,
      cooldownMs: 8000,
      requiredLevel: 6,
      targetType: 'targeted',
      targetKind: 'player',
      resourceCost: 40,
      baseValue: 8,
      coefficient: 0.4,
      hotTicks: 8,
      hotDurationMs: 8000,
      supportTag: true,
    },
    {
      id: 'cleanse',
      name: 'Cleanse',
      slot: 5,
      cooldownMs: 12000,
      requiredLevel: 10,
      targetType: 'targeted',
      targetKind: 'player',
      resourceCost: 35,
    },
    {
      id: 'divine_shield',
      name: 'Divine Shield',
      slot: 6,
      cooldownMs: 30000,
      requiredLevel: 15,
      targetType: 'targeted',
      targetKind: 'player',
      resourceCost: 50,
      baseValue: 20,
      coefficient: 0.8,
      supportTag: true,
    },
    {
      id: 'prayer_of_light',
      name: 'Prayer of Light',
      slot: 7,
      cooldownMs: 20000,
      requiredLevel: 20,
      targetType: 'aoe',
      resourceCost: 60,
      baseValue: 12,
      coefficient: 0.5,
      radius: 5,
      pvpHealMultiplier: 0.8,
      requirePlacement: true,
      placementRange: 10,
    },
    {
      id: 'silence',
      name: 'Silence',
      slot: 8,
      cooldownMs: 24000,
      requiredLevel: 25,
      targetType: 'targeted',
      targetKind: 'player',
      resourceCost: 40,
      interruptLockoutMs: 2000,
    },
    {
      id: 'salvation',
      name: 'Salvation',
      slot: 9,
      cooldownMs: 300000,
      requiredLevel: 30,
      targetType: 'targeted',
      targetKind: 'player',
      resourceCost: 100,
    },
  ],
  mage: [
    {
      id: 'firebolt',
      name: 'Firebolt',
      slot: 2,
      cooldownMs: 5000,
      requiredLevel: 2,
      targetType: 'targeted',
      targetKind: 'any',
      attackType: 'ranged',
      resourceCost: 40,
      baseValue: 15,
      coefficient: 0.9,
      pvpDamageMultiplier: 0.8,
      rangeMultiplier: 1.3,
    },
    {
      id: 'frost_nova',
      name: 'Frost Nova',
      slot: 3,
      cooldownMs: 12000,
      requiredLevel: 3,
      targetType: 'aoe',
      resourceCost: 50,
      baseValue: 8,
      coefficient: 0.4,
      radius: 2.5,
      slowPct: 50,
      durationMs: 3000,
      pvpCCDurationMultiplier: 0.6,
    },
    {
      id: 'arcane_missiles',
      name: 'Arcane Missiles',
      slot: 4,
      cooldownMs: 12000,
      requiredLevel: 6,
      targetType: 'targeted',
      targetKind: 'mob',
      attackType: 'ranged',
      resourceCost: 45,
      windUpMs: 1500,
      channelTicks: 3,
      baseValue: 10,
      coefficient: 0.4,
    },
    {
      id: 'flame_wave',
      name: 'Flame Wave',
      slot: 5,
      cooldownMs: 15000,
      requiredLevel: 10,
      targetType: 'aoe',
      resourceCost: 50,
      baseValue: 14,
      coefficient: 0.55,
      coneDegrees: 90,
      range: 5,
    },
    {
      id: 'ice_barrier',
      name: 'Ice Barrier',
      slot: 6,
      cooldownMs: 45000,
      requiredLevel: 15,
      targetType: 'self',
      resourceCost: 55,
      baseValue: 25,
      coefficient: 0.9,
    },
    {
      id: 'blink',
      name: 'Blink',
      slot: 7,
      cooldownMs: 24000,
      requiredLevel: 20,
      targetType: 'self',
      resourceCost: 40,
      dashDistance: 4,
      exemptFromGCD: true,
    },
    {
      id: 'counterspell',
      name: 'Counterspell',
      slot: 8,
      cooldownMs: 24000,
      requiredLevel: 25,
      targetType: 'targeted',
      targetKind: 'any',
      resourceCost: 35,
      interruptLockoutMs: 2000,
    },
    {
      id: 'meteor',
      name: 'Meteor',
      slot: 9,
      cooldownMs: 60000,
      requiredLevel: 30,
      targetType: 'aoe',
      resourceCost: 80,
      baseValue: 25,
      coefficient: 0.8,
      radius: 4,
      pvpDamageMultiplier: 0.7,
      requirePlacement: true,
      placementRange: 12,
    },
  ],
};

export function resolveAbilityRange(template, baseRange) {
  if (Number.isFinite(template?.range)) return template.range;
  if (Number.isFinite(template?.rangeMultiplier)) {
    return baseRange * template.rangeMultiplier;
  }
  return baseRange;
}
